blank_issues_enabled: true
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/ajaynegi45/himalayan-echoes/discussions
    about: Please use discussions for general questions or brainstorming.
